services:
  booking-api-system:
    image: booking-api:latest
    container_name: booking-system-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./env:./opt/app/.env
  mongodb:
    image: mongo
    container_name: bookingdb
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  mongo-data: